export const randomSentences = [
  "The quick brown fox jumps over the lazy dog.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "The sky is blue and the sun is shining brightly.",
  "I enjoy reading books in my free time.",
  "She danced gracefully across the stage.",
  "Life is like a box of chocolates, you never know what you're gonna get.",
  "The world is full of possibilities.",
  "Coding is both challenging and rewarding.",
  "He traveled to faraway lands in search of adventure.",
  "Learning new skills broadens your horizons.",
  "The clock struck midnight and the party was over.",
  "The storm raged outside, but we were safe indoors.",
  "Love is patient, love is kind.",
  "The mountains loomed majestically in the distance.",
  "She whispered secrets to the wind.",
  "Laughter is the best medicine.",
  "The moonlight cast a magical glow over the landscape.",
  "We gazed at the stars in wonder.",
  "The sound of waves crashing against the shore was soothing.",
  "He took a deep breath and plunged into the icy water.",
  "The city never sleeps.",
  "It is easier to live through someone else than to become complete yourself."
];
