export const TYPER_CONTAINER_TEST_ID = 'TYPER_CONTAINER_TEST_ID';
export const TYPER_DISPLAY_FIELD_TEST_ID = 'TYPER_DISPLAY_FIELD_TEST_ID';
export const TYPER_INPUT_ELEMENT_TEST_ID = 'TYPER_INPUT_ELEMENT_TEST_ID';